name:                dlackware
version:             1.0.0.0
github:              "Dlackware/dlackware"
license:             GPL-3
author:              "Eugene Wissner"
maintainer:          "info@dlackware.com"
copyright:           "2018-2019 Eugene Wissner"

extra-source-files:
- README.md
- COPYING

description: Dlackware Gnome build system and installer

dependencies:
- ansi-terminal
- base >= 4.7 && < 5
- bytestring
- cryptonite
- cryptonite-conduit
- filepath
- process
- HsYAML
- optparse-applicative
- directory
- conduit
- conduit-extra
- data-default-class
- megaparsec
- parser-combinators
- req
- req-conduit
- text
- transformers

library:
    source-dirs: lib

executables:
  dlackware:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dlackware

tests:
  dlackware-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dlackware
    - hspec
